
#spring:

#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    defer-datasource-initialization: true
#    show-sql: true
#    properties:
#      hibernate:
##        dialect: H2Dialect
#        dialect: org.hibernate.dialect.H2Dialect
##        dialect: org.hibernate.dialect.MySQL5Dialect
#        format_sql: true
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:demo;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:

#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: ${client-id}
#            client-secret: ${client-secret}
#            authorization-grant-type: authorization_code
#            scope: openid
#
#        provider:
#          keycloak:
#            issuer-uri: ${oauth2-client-keycloak}/realms/${client-realm}
#            user-name-attribute: preferred_username
#
#      resource-server:
#        jwt:
#          issuer-uri: ${oauth2-client-keycloak}/realms/${client-realm}


#logging:
#  level:
#    org.springframework.web: TRACE
#    com.siukatech.poc.react.backend.module.core: TRACE


